/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_STUB_H
#define _MOCK_STUB_H

#include "unity.h"
#include "stub.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_stub_Init(void);
void mock_stub_Destroy(void);
void mock_stub_Verify(void);




#define CanIf_TxConfirmation_Ignore() CanIf_TxConfirmation_CMockIgnore()
void CanIf_TxConfirmation_CMockIgnore(void);
#define CanIf_TxConfirmation_StopIgnore() CanIf_TxConfirmation_CMockStopIgnore()
void CanIf_TxConfirmation_CMockStopIgnore(void);
#define CanIf_TxConfirmation_ExpectAnyArgs() CanIf_TxConfirmation_CMockExpectAnyArgs(__LINE__)
void CanIf_TxConfirmation_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define CanIf_TxConfirmation_Expect(CanTxPduId) CanIf_TxConfirmation_CMockExpect(__LINE__, CanTxPduId)
void CanIf_TxConfirmation_CMockExpect(UNITY_LINE_TYPE cmock_line, PduIdType CanTxPduId);
typedef void (* CMOCK_CanIf_TxConfirmation_CALLBACK)(PduIdType CanTxPduId, int cmock_num_calls);
void CanIf_TxConfirmation_AddCallback(CMOCK_CanIf_TxConfirmation_CALLBACK Callback);
void CanIf_TxConfirmation_Stub(CMOCK_CanIf_TxConfirmation_CALLBACK Callback);
#define CanIf_TxConfirmation_StubWithCallback CanIf_TxConfirmation_Stub
#define CanIf_TxConfirmation_IgnoreArg_CanTxPduId() CanIf_TxConfirmation_CMockIgnoreArg_CanTxPduId(__LINE__)
void CanIf_TxConfirmation_CMockIgnoreArg_CanTxPduId(UNITY_LINE_TYPE cmock_line);
#define CanIf_ControllerModeIndication_Ignore() CanIf_ControllerModeIndication_CMockIgnore()
void CanIf_ControllerModeIndication_CMockIgnore(void);
#define CanIf_ControllerModeIndication_StopIgnore() CanIf_ControllerModeIndication_CMockStopIgnore()
void CanIf_ControllerModeIndication_CMockStopIgnore(void);
#define CanIf_ControllerModeIndication_ExpectAnyArgs() CanIf_ControllerModeIndication_CMockExpectAnyArgs(__LINE__)
void CanIf_ControllerModeIndication_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define CanIf_ControllerModeIndication_Expect(ControllerId, ControllerMode) CanIf_ControllerModeIndication_CMockExpect(__LINE__, ControllerId, ControllerMode)
void CanIf_ControllerModeIndication_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8 ControllerId, Can_ControllerStateType ControllerMode);
typedef void (* CMOCK_CanIf_ControllerModeIndication_CALLBACK)(uint8 ControllerId, Can_ControllerStateType ControllerMode, int cmock_num_calls);
void CanIf_ControllerModeIndication_AddCallback(CMOCK_CanIf_ControllerModeIndication_CALLBACK Callback);
void CanIf_ControllerModeIndication_Stub(CMOCK_CanIf_ControllerModeIndication_CALLBACK Callback);
#define CanIf_ControllerModeIndication_StubWithCallback CanIf_ControllerModeIndication_Stub
#define CanIf_ControllerModeIndication_IgnoreArg_ControllerId() CanIf_ControllerModeIndication_CMockIgnoreArg_ControllerId(__LINE__)
void CanIf_ControllerModeIndication_CMockIgnoreArg_ControllerId(UNITY_LINE_TYPE cmock_line);
#define CanIf_ControllerModeIndication_IgnoreArg_ControllerMode() CanIf_ControllerModeIndication_CMockIgnoreArg_ControllerMode(__LINE__)
void CanIf_ControllerModeIndication_CMockIgnoreArg_ControllerMode(UNITY_LINE_TYPE cmock_line);
#define CanIf_RxIndication_Ignore() CanIf_RxIndication_CMockIgnore()
void CanIf_RxIndication_CMockIgnore(void);
#define CanIf_RxIndication_StopIgnore() CanIf_RxIndication_CMockStopIgnore()
void CanIf_RxIndication_CMockStopIgnore(void);
#define CanIf_RxIndication_ExpectAnyArgs() CanIf_RxIndication_CMockExpectAnyArgs(__LINE__)
void CanIf_RxIndication_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define CanIf_RxIndication_Expect(Mailbox, PduInfoPtr) CanIf_RxIndication_CMockExpect(__LINE__, Mailbox, PduInfoPtr)
void CanIf_RxIndication_CMockExpect(UNITY_LINE_TYPE cmock_line, const Can_HwType* Mailbox, const PduInfoType* PduInfoPtr);
typedef void (* CMOCK_CanIf_RxIndication_CALLBACK)(const Can_HwType* Mailbox, const PduInfoType* PduInfoPtr, int cmock_num_calls);
void CanIf_RxIndication_AddCallback(CMOCK_CanIf_RxIndication_CALLBACK Callback);
void CanIf_RxIndication_Stub(CMOCK_CanIf_RxIndication_CALLBACK Callback);
#define CanIf_RxIndication_StubWithCallback CanIf_RxIndication_Stub
#define CanIf_RxIndication_ExpectWithArray(Mailbox, Mailbox_Depth, PduInfoPtr, PduInfoPtr_Depth) CanIf_RxIndication_CMockExpectWithArray(__LINE__, Mailbox, Mailbox_Depth, PduInfoPtr, PduInfoPtr_Depth)
void CanIf_RxIndication_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, const Can_HwType* Mailbox, int Mailbox_Depth, const PduInfoType* PduInfoPtr, int PduInfoPtr_Depth);
#define CanIf_RxIndication_IgnoreArg_Mailbox() CanIf_RxIndication_CMockIgnoreArg_Mailbox(__LINE__)
void CanIf_RxIndication_CMockIgnoreArg_Mailbox(UNITY_LINE_TYPE cmock_line);
#define CanIf_RxIndication_IgnoreArg_PduInfoPtr() CanIf_RxIndication_CMockIgnoreArg_PduInfoPtr(__LINE__)
void CanIf_RxIndication_CMockIgnoreArg_PduInfoPtr(UNITY_LINE_TYPE cmock_line);
#define CanIf_ControllerBusOff_Ignore() CanIf_ControllerBusOff_CMockIgnore()
void CanIf_ControllerBusOff_CMockIgnore(void);
#define CanIf_ControllerBusOff_StopIgnore() CanIf_ControllerBusOff_CMockStopIgnore()
void CanIf_ControllerBusOff_CMockStopIgnore(void);
#define CanIf_ControllerBusOff_ExpectAnyArgs() CanIf_ControllerBusOff_CMockExpectAnyArgs(__LINE__)
void CanIf_ControllerBusOff_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define CanIf_ControllerBusOff_Expect(ControllerId) CanIf_ControllerBusOff_CMockExpect(__LINE__, ControllerId)
void CanIf_ControllerBusOff_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8 ControllerId);
typedef void (* CMOCK_CanIf_ControllerBusOff_CALLBACK)(uint8 ControllerId, int cmock_num_calls);
void CanIf_ControllerBusOff_AddCallback(CMOCK_CanIf_ControllerBusOff_CALLBACK Callback);
void CanIf_ControllerBusOff_Stub(CMOCK_CanIf_ControllerBusOff_CALLBACK Callback);
#define CanIf_ControllerBusOff_StubWithCallback CanIf_ControllerBusOff_Stub
#define CanIf_ControllerBusOff_IgnoreArg_ControllerId() CanIf_ControllerBusOff_CMockIgnoreArg_ControllerId(__LINE__)
void CanIf_ControllerBusOff_CMockIgnoreArg_ControllerId(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
