/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_TEST_CAN_SWC_STUBS_H
#define _MOCK_TEST_CAN_SWC_STUBS_H

#include "unity.h"
#include "test_can_swc_stubs.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_test_can_swc_stubs_Init(void);
void mock_test_can_swc_stubs_Destroy(void);
void mock_test_can_swc_stubs_Verify(void);




#define irq_Enable_Ignore() irq_Enable_CMockIgnore()
void irq_Enable_CMockIgnore(void);
#define irq_Enable_StopIgnore() irq_Enable_CMockStopIgnore()
void irq_Enable_CMockStopIgnore(void);
#define irq_Enable_Expect() irq_Enable_CMockExpect(__LINE__)
void irq_Enable_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_irq_Enable_CALLBACK)(int cmock_num_calls);
void irq_Enable_AddCallback(CMOCK_irq_Enable_CALLBACK Callback);
void irq_Enable_Stub(CMOCK_irq_Enable_CALLBACK Callback);
#define irq_Enable_StubWithCallback irq_Enable_Stub
#define irq_Disable_Ignore() irq_Disable_CMockIgnore()
void irq_Disable_CMockIgnore(void);
#define irq_Disable_StopIgnore() irq_Disable_CMockStopIgnore()
void irq_Disable_CMockStopIgnore(void);
#define irq_Disable_Expect() irq_Disable_CMockExpect(__LINE__)
void irq_Disable_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_irq_Disable_CALLBACK)(int cmock_num_calls);
void irq_Disable_AddCallback(CMOCK_irq_Disable_CALLBACK Callback);
void irq_Disable_Stub(CMOCK_irq_Disable_CALLBACK Callback);
#define irq_Disable_StubWithCallback irq_Disable_Stub
#define __DSB_Ignore() __DSB_CMockIgnore()
void __DSB_CMockIgnore(void);
#define __DSB_StopIgnore() __DSB_CMockStopIgnore()
void __DSB_CMockStopIgnore(void);
#define __DSB_Expect() __DSB_CMockExpect(__LINE__)
void __DSB_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK___DSB_CALLBACK)(int cmock_num_calls);
void __DSB_AddCallback(CMOCK___DSB_CALLBACK Callback);
void __DSB_Stub(CMOCK___DSB_CALLBACK Callback);
#define __DSB_StubWithCallback __DSB_Stub
#define __NOP_Ignore() __NOP_CMockIgnore()
void __NOP_CMockIgnore(void);
#define __NOP_StopIgnore() __NOP_CMockStopIgnore()
void __NOP_CMockStopIgnore(void);
#define __NOP_Expect() __NOP_CMockExpect(__LINE__)
void __NOP_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK___NOP_CALLBACK)(int cmock_num_calls);
void __NOP_AddCallback(CMOCK___NOP_CALLBACK Callback);
void __NOP_Stub(CMOCK___NOP_CALLBACK Callback);
#define __NOP_StubWithCallback __NOP_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
