/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_test_can_swc_stubs.h"

static const char* CMockString___DSB = "__DSB";
static const char* CMockString___NOP = "__NOP";
static const char* CMockString_irq_Disable = "irq_Disable";
static const char* CMockString_irq_Enable = "irq_Enable";

typedef struct _CMOCK_irq_Enable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_irq_Enable_CALL_INSTANCE;

typedef struct _CMOCK_irq_Disable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_irq_Disable_CALL_INSTANCE;

typedef struct _CMOCK___DSB_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK___DSB_CALL_INSTANCE;

typedef struct _CMOCK___NOP_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK___NOP_CALL_INSTANCE;

static struct mock_test_can_swc_stubsInstance
{
  char irq_Enable_IgnoreBool;
  char irq_Enable_CallbackBool;
  CMOCK_irq_Enable_CALLBACK irq_Enable_CallbackFunctionPointer;
  int irq_Enable_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE irq_Enable_CallInstance;
  char irq_Disable_IgnoreBool;
  char irq_Disable_CallbackBool;
  CMOCK_irq_Disable_CALLBACK irq_Disable_CallbackFunctionPointer;
  int irq_Disable_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE irq_Disable_CallInstance;
  char __DSB_IgnoreBool;
  char __DSB_CallbackBool;
  CMOCK___DSB_CALLBACK __DSB_CallbackFunctionPointer;
  int __DSB_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE __DSB_CallInstance;
  char __NOP_IgnoreBool;
  char __NOP_CallbackBool;
  CMOCK___NOP_CALLBACK __NOP_CallbackFunctionPointer;
  int __NOP_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE __NOP_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_test_can_swc_stubs_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.irq_Enable_CallInstance;
  if (Mock.irq_Enable_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_irq_Enable);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.irq_Enable_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.irq_Disable_CallInstance;
  if (Mock.irq_Disable_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_irq_Disable);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.irq_Disable_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.__DSB_CallInstance;
  if (Mock.__DSB_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString___DSB);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.__DSB_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.__NOP_CallInstance;
  if (Mock.__NOP_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString___NOP);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.__NOP_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_test_can_swc_stubs_Init(void)
{
  mock_test_can_swc_stubs_Destroy();
}

void mock_test_can_swc_stubs_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void irq_Enable(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_irq_Enable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_irq_Enable);
  cmock_call_instance = (CMOCK_irq_Enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.irq_Enable_CallInstance);
  Mock.irq_Enable_CallInstance = CMock_Guts_MemNext(Mock.irq_Enable_CallInstance);
  if (Mock.irq_Enable_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.irq_Enable_CallbackBool &&
      Mock.irq_Enable_CallbackFunctionPointer != NULL)
  {
    Mock.irq_Enable_CallbackFunctionPointer(Mock.irq_Enable_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.irq_Enable_CallbackFunctionPointer != NULL)
  {
    Mock.irq_Enable_CallbackFunctionPointer(Mock.irq_Enable_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void irq_Enable_CMockIgnore(void)
{
  Mock.irq_Enable_IgnoreBool = (char)1;
}

void irq_Enable_CMockStopIgnore(void)
{
  Mock.irq_Enable_IgnoreBool = (char)0;
}

void irq_Enable_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_irq_Enable_CALL_INSTANCE));
  CMOCK_irq_Enable_CALL_INSTANCE* cmock_call_instance = (CMOCK_irq_Enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.irq_Enable_CallInstance = CMock_Guts_MemChain(Mock.irq_Enable_CallInstance, cmock_guts_index);
  Mock.irq_Enable_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void irq_Enable_AddCallback(CMOCK_irq_Enable_CALLBACK Callback)
{
  Mock.irq_Enable_IgnoreBool = (char)0;
  Mock.irq_Enable_CallbackBool = (char)1;
  Mock.irq_Enable_CallbackFunctionPointer = Callback;
}

void irq_Enable_Stub(CMOCK_irq_Enable_CALLBACK Callback)
{
  Mock.irq_Enable_IgnoreBool = (char)0;
  Mock.irq_Enable_CallbackBool = (char)0;
  Mock.irq_Enable_CallbackFunctionPointer = Callback;
}

void irq_Disable(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_irq_Disable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_irq_Disable);
  cmock_call_instance = (CMOCK_irq_Disable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.irq_Disable_CallInstance);
  Mock.irq_Disable_CallInstance = CMock_Guts_MemNext(Mock.irq_Disable_CallInstance);
  if (Mock.irq_Disable_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.irq_Disable_CallbackBool &&
      Mock.irq_Disable_CallbackFunctionPointer != NULL)
  {
    Mock.irq_Disable_CallbackFunctionPointer(Mock.irq_Disable_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.irq_Disable_CallbackFunctionPointer != NULL)
  {
    Mock.irq_Disable_CallbackFunctionPointer(Mock.irq_Disable_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void irq_Disable_CMockIgnore(void)
{
  Mock.irq_Disable_IgnoreBool = (char)1;
}

void irq_Disable_CMockStopIgnore(void)
{
  Mock.irq_Disable_IgnoreBool = (char)0;
}

void irq_Disable_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_irq_Disable_CALL_INSTANCE));
  CMOCK_irq_Disable_CALL_INSTANCE* cmock_call_instance = (CMOCK_irq_Disable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.irq_Disable_CallInstance = CMock_Guts_MemChain(Mock.irq_Disable_CallInstance, cmock_guts_index);
  Mock.irq_Disable_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void irq_Disable_AddCallback(CMOCK_irq_Disable_CALLBACK Callback)
{
  Mock.irq_Disable_IgnoreBool = (char)0;
  Mock.irq_Disable_CallbackBool = (char)1;
  Mock.irq_Disable_CallbackFunctionPointer = Callback;
}

void irq_Disable_Stub(CMOCK_irq_Disable_CALLBACK Callback)
{
  Mock.irq_Disable_IgnoreBool = (char)0;
  Mock.irq_Disable_CallbackBool = (char)0;
  Mock.irq_Disable_CallbackFunctionPointer = Callback;
}

void __DSB(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK___DSB_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString___DSB);
  cmock_call_instance = (CMOCK___DSB_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.__DSB_CallInstance);
  Mock.__DSB_CallInstance = CMock_Guts_MemNext(Mock.__DSB_CallInstance);
  if (Mock.__DSB_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.__DSB_CallbackBool &&
      Mock.__DSB_CallbackFunctionPointer != NULL)
  {
    Mock.__DSB_CallbackFunctionPointer(Mock.__DSB_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.__DSB_CallbackFunctionPointer != NULL)
  {
    Mock.__DSB_CallbackFunctionPointer(Mock.__DSB_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void __DSB_CMockIgnore(void)
{
  Mock.__DSB_IgnoreBool = (char)1;
}

void __DSB_CMockStopIgnore(void)
{
  Mock.__DSB_IgnoreBool = (char)0;
}

void __DSB_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK___DSB_CALL_INSTANCE));
  CMOCK___DSB_CALL_INSTANCE* cmock_call_instance = (CMOCK___DSB_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.__DSB_CallInstance = CMock_Guts_MemChain(Mock.__DSB_CallInstance, cmock_guts_index);
  Mock.__DSB_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void __DSB_AddCallback(CMOCK___DSB_CALLBACK Callback)
{
  Mock.__DSB_IgnoreBool = (char)0;
  Mock.__DSB_CallbackBool = (char)1;
  Mock.__DSB_CallbackFunctionPointer = Callback;
}

void __DSB_Stub(CMOCK___DSB_CALLBACK Callback)
{
  Mock.__DSB_IgnoreBool = (char)0;
  Mock.__DSB_CallbackBool = (char)0;
  Mock.__DSB_CallbackFunctionPointer = Callback;
}

void __NOP(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK___NOP_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString___NOP);
  cmock_call_instance = (CMOCK___NOP_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.__NOP_CallInstance);
  Mock.__NOP_CallInstance = CMock_Guts_MemNext(Mock.__NOP_CallInstance);
  if (Mock.__NOP_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.__NOP_CallbackBool &&
      Mock.__NOP_CallbackFunctionPointer != NULL)
  {
    Mock.__NOP_CallbackFunctionPointer(Mock.__NOP_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.__NOP_CallbackFunctionPointer != NULL)
  {
    Mock.__NOP_CallbackFunctionPointer(Mock.__NOP_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void __NOP_CMockIgnore(void)
{
  Mock.__NOP_IgnoreBool = (char)1;
}

void __NOP_CMockStopIgnore(void)
{
  Mock.__NOP_IgnoreBool = (char)0;
}

void __NOP_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK___NOP_CALL_INSTANCE));
  CMOCK___NOP_CALL_INSTANCE* cmock_call_instance = (CMOCK___NOP_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.__NOP_CallInstance = CMock_Guts_MemChain(Mock.__NOP_CallInstance, cmock_guts_index);
  Mock.__NOP_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void __NOP_AddCallback(CMOCK___NOP_CALLBACK Callback)
{
  Mock.__NOP_IgnoreBool = (char)0;
  Mock.__NOP_CallbackBool = (char)1;
  Mock.__NOP_CallbackFunctionPointer = Callback;
}

void __NOP_Stub(CMOCK___NOP_CALLBACK Callback)
{
  Mock.__NOP_IgnoreBool = (char)0;
  Mock.__NOP_CallbackBool = (char)0;
  Mock.__NOP_CallbackFunctionPointer = Callback;
}

