/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_Det.h"

static const char* CMockString_ApiId = "ApiId";
static const char* CMockString_Det_ReportError = "Det_ReportError";
static const char* CMockString_ErrorId = "ErrorId";
static const char* CMockString_InstanceId = "InstanceId";
static const char* CMockString_ModuleId = "ModuleId";

typedef struct _CMOCK_Det_ReportError_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  Std_ReturnType ReturnVal;
  uint16 Expected_ModuleId;
  uint8 Expected_InstanceId;
  uint8 Expected_ApiId;
  uint8 Expected_ErrorId;
  char IgnoreArg_ModuleId;
  char IgnoreArg_InstanceId;
  char IgnoreArg_ApiId;
  char IgnoreArg_ErrorId;

} CMOCK_Det_ReportError_CALL_INSTANCE;

static struct mock_DetInstance
{
  char Det_ReportError_IgnoreBool;
  Std_ReturnType Det_ReportError_FinalReturn;
  char Det_ReportError_CallbackBool;
  CMOCK_Det_ReportError_CALLBACK Det_ReportError_CallbackFunctionPointer;
  int Det_ReportError_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Det_ReportError_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_Det_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.Det_ReportError_CallInstance;
  if (Mock.Det_ReportError_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Det_ReportError);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Det_ReportError_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_Det_Init(void)
{
  mock_Det_Destroy();
}

void mock_Det_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

Std_ReturnType Det_ReportError(uint16 ModuleId, uint8 InstanceId, uint8 ApiId, uint8 ErrorId)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Det_ReportError_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Det_ReportError);
  cmock_call_instance = (CMOCK_Det_ReportError_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Det_ReportError_CallInstance);
  Mock.Det_ReportError_CallInstance = CMock_Guts_MemNext(Mock.Det_ReportError_CallInstance);
  if (Mock.Det_ReportError_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.Det_ReportError_FinalReturn;
    memcpy((void*)(&Mock.Det_ReportError_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(Std_ReturnType[sizeof(cmock_call_instance->ReturnVal) == sizeof(Std_ReturnType) ? 1 : -1])); /* add Std_ReturnType to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.Det_ReportError_CallbackBool &&
      Mock.Det_ReportError_CallbackFunctionPointer != NULL)
  {
    Std_ReturnType cmock_cb_ret = Mock.Det_ReportError_CallbackFunctionPointer(ModuleId, InstanceId, ApiId, ErrorId, Mock.Det_ReportError_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_ModuleId)
  {
    UNITY_SET_DETAILS(CMockString_Det_ReportError,CMockString_ModuleId);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_ModuleId, ModuleId, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_InstanceId)
  {
    UNITY_SET_DETAILS(CMockString_Det_ReportError,CMockString_InstanceId);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_InstanceId, InstanceId, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_ApiId)
  {
    UNITY_SET_DETAILS(CMockString_Det_ReportError,CMockString_ApiId);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_ApiId, ApiId, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_ErrorId)
  {
    UNITY_SET_DETAILS(CMockString_Det_ReportError,CMockString_ErrorId);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_ErrorId, ErrorId, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.Det_ReportError_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.Det_ReportError_CallbackFunctionPointer(ModuleId, InstanceId, ApiId, ErrorId, Mock.Det_ReportError_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Det_ReportError(CMOCK_Det_ReportError_CALL_INSTANCE* cmock_call_instance, uint16 ModuleId, uint8 InstanceId, uint8 ApiId, uint8 ErrorId);
void CMockExpectParameters_Det_ReportError(CMOCK_Det_ReportError_CALL_INSTANCE* cmock_call_instance, uint16 ModuleId, uint8 InstanceId, uint8 ApiId, uint8 ErrorId)
{
  cmock_call_instance->Expected_ModuleId = ModuleId;
  cmock_call_instance->IgnoreArg_ModuleId = 0;
  cmock_call_instance->Expected_InstanceId = InstanceId;
  cmock_call_instance->IgnoreArg_InstanceId = 0;
  cmock_call_instance->Expected_ApiId = ApiId;
  cmock_call_instance->IgnoreArg_ApiId = 0;
  cmock_call_instance->Expected_ErrorId = ErrorId;
  cmock_call_instance->IgnoreArg_ErrorId = 0;
}

void Det_ReportError_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, Std_ReturnType cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Det_ReportError_CALL_INSTANCE));
  CMOCK_Det_ReportError_CALL_INSTANCE* cmock_call_instance = (CMOCK_Det_ReportError_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Det_ReportError_CallInstance = CMock_Guts_MemChain(Mock.Det_ReportError_CallInstance, cmock_guts_index);
  Mock.Det_ReportError_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Det_ReportError_IgnoreBool = (char)1;
}

void Det_ReportError_CMockStopIgnore(void)
{
  if(Mock.Det_ReportError_IgnoreBool)
    Mock.Det_ReportError_CallInstance = CMock_Guts_MemNext(Mock.Det_ReportError_CallInstance);
  Mock.Det_ReportError_IgnoreBool = (char)0;
}

void Det_ReportError_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, Std_ReturnType cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Det_ReportError_CALL_INSTANCE));
  CMOCK_Det_ReportError_CALL_INSTANCE* cmock_call_instance = (CMOCK_Det_ReportError_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Det_ReportError_CallInstance = CMock_Guts_MemChain(Mock.Det_ReportError_CallInstance, cmock_guts_index);
  Mock.Det_ReportError_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void Det_ReportError_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16 ModuleId, uint8 InstanceId, uint8 ApiId, uint8 ErrorId, Std_ReturnType cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Det_ReportError_CALL_INSTANCE));
  CMOCK_Det_ReportError_CALL_INSTANCE* cmock_call_instance = (CMOCK_Det_ReportError_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Det_ReportError_CallInstance = CMock_Guts_MemChain(Mock.Det_ReportError_CallInstance, cmock_guts_index);
  Mock.Det_ReportError_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_Det_ReportError(cmock_call_instance, ModuleId, InstanceId, ApiId, ErrorId);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(Std_ReturnType[sizeof(cmock_to_return) == sizeof(Std_ReturnType) ? 1 : -1])); /* add Std_ReturnType to :treat_as_array if this causes an error */
}

void Det_ReportError_AddCallback(CMOCK_Det_ReportError_CALLBACK Callback)
{
  Mock.Det_ReportError_IgnoreBool = (char)0;
  Mock.Det_ReportError_CallbackBool = (char)1;
  Mock.Det_ReportError_CallbackFunctionPointer = Callback;
}

void Det_ReportError_Stub(CMOCK_Det_ReportError_CALLBACK Callback)
{
  Mock.Det_ReportError_IgnoreBool = (char)0;
  Mock.Det_ReportError_CallbackBool = (char)0;
  Mock.Det_ReportError_CallbackFunctionPointer = Callback;
}

void Det_ReportError_CMockIgnoreArg_ModuleId(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Det_ReportError_CALL_INSTANCE* cmock_call_instance = (CMOCK_Det_ReportError_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Det_ReportError_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ModuleId = 1;
}

void Det_ReportError_CMockIgnoreArg_InstanceId(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Det_ReportError_CALL_INSTANCE* cmock_call_instance = (CMOCK_Det_ReportError_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Det_ReportError_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_InstanceId = 1;
}

void Det_ReportError_CMockIgnoreArg_ApiId(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Det_ReportError_CALL_INSTANCE* cmock_call_instance = (CMOCK_Det_ReportError_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Det_ReportError_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ApiId = 1;
}

void Det_ReportError_CMockIgnoreArg_ErrorId(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_Det_ReportError_CALL_INSTANCE* cmock_call_instance = (CMOCK_Det_ReportError_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.Det_ReportError_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ErrorId = 1;
}

