/*******************************************************************************
**                                                                            **
**  Copyright (C) AUTOSarZs olc (2019)		                                  **
**                                                                            **
**  All rights reserved.                                                      **
**                                                                            **
**  This document contains proprietary information belonging to AUTOSarZs     **
**  olc . Passing on and copying of this document, and communication          **
**  of its contents is not permitted without prior written authorization.     **
**                                                                            **
********************************************************************************
**                                                                            **
**  FILENAME     : irq.c         			                                  **
**                                                                            **
**  VERSION      : 1.0.0                                                      **
**                                                                            **
**  DATE         : 2019-09-22                                                 **
**                                                                            **
**  VARIANT      : Variant PB                                                 **
**                                                                            **
**  PLATFORM     : TIVA C		                                              **
**                                                                            **
**  AUTHOR       : AUTOSarZs-DevTeam	                                      **
**                                                                            **
**  VENDOR       : AUTOSarZs OLC	                                          **
**                                                                            **
**                                                                            **
**  DESCRIPTION  : CAN Driver source file                                     **
**                                                                            **
**  SPECIFICATION(S) : Specification of CAN Driver, AUTOSAR Release 4.3.1     **
**                                                                            **
**  MAY BE CHANGED BY USER : no                                               **
**                                                                            **
*******************************************************************************/

/* For GNU GCC Compiler :
 * naked: This attribute allows the compiler to construct the requisite function declaration,
 * while allowing the body of the function to be assembly code. The
 * specified function will not have prologue/epilogue sequences generated by the
 * compiler. Only basic asm statements can safely be included in naked functions.
 * While using extended asm or a mixture of basic asm and C code may appear to work,
 * they cannot be depended upon to work reliably and are not supported.
 */
/* Enable all interrupts */
__attribute__((naked)) void irq_Enable(void)
{
	__asm(" CPSIE I");
	__asm(" BX LR") ;
}

/* Disable all interrupts */

__attribute__((naked)) void irq_Disable(void)
{
    __asm(" CPSID I");
    __asm(" BX LR") ;
}
